### ISSUE TITLE
bay area seniors computer club maybe interested in a LUG?

### ISSUE THREAD

**Issue by a-schaefers** [cooslug/cooslug.github.io#11]
I found another local group, i am not sure if it is still active, but I hope they are still wanting to do this! :-)
 https://sites.google.com/site/bayareaseniorscomputerclub/

It states, 

> 
>     Linux users - If you are interested in this operating system, we are interested in hearing about it. We are beginning to put together a Linux User Group in Coos Bay and surrounding area. Please let us know about your experience or desire to be involved.
>     For contact, Call Rene Reulet, 541-269-7396, or J.R. Moore, 541-888-8752

**Comment by bayprogrammer** [comment]
Hey, if they're already working on it then maybe we can join forces. Certainly worth checking out.

**Comment by a-schaefers** [comment]
definitely, i'll reach out them soon to see what is the status

**Comment by a-schaefers** [comment]
Yo dude, check out my page. https://www.funtoo.org/Libvirt

woot
